"""empty message

Revision ID: 7fa80a31a9e5
Revises: 1a6207565797
Create Date: 2021-02-24 19:33:07.308212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa80a31a9e5'
down_revision = '1a6207565797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'projectId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'projectId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
