"""empty message

Revision ID: c74b2051e280
Revises: ffdc0a98111c
Create Date: 2021-02-19 19:25:00.459460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74b2051e280'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectName', sa.String(length=100), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=False),
    sa.Column('taskId', sa.Integer(), nullable=False),
    sa.Column('teamName', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taskTitle', sa.String(length=100), nullable=False),
    sa.Column('dueDate', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('assigneeId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigneeId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('about', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('firstName', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('lastName', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('photoUrl', sa.String(), nullable=True))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'photoUrl')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    op.drop_column('users', 'about')
    op.drop_table('tasks')
    op.drop_table('members')
    op.drop_table('projects')
    # ### end Alembic commands ###
