"""empty message

Revision ID: 5f9f6e60d776
Revises: c74b2051e280
Create Date: 2021-02-24 23:40:57.184324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9f6e60d776'
down_revision = 'c74b2051e280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'projectId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'projectId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
