"""empty message

Revision ID: 1a6207565797
Revises: c74b2051e280
Create Date: 2021-02-24 18:05:04.217940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6207565797'
down_revision = 'c74b2051e280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'taskId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('taskId', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
